security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User: auto

    providers:
        chain_provider:
            chain:
                providers: [kimai_internal]
#                providers: [kimai_internal,kimai_ldap]
        kimai_internal:
            entity:
                class: App\Entity\User
#        kimai_ldap:
#            id: App\Ldap\LdapUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
#            kimai_ldap: ~
            pattern: ^/
            user_checker: App\Security\UserChecker
            stateless: false

            entry_point: form_login

            custom_authenticators:
                - App\API\Authentication\ApiAuthenticator
                - App\Saml\SamlAuthenticator

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /

            # activate all configured user provider
            provider: chain_provider

            form_login:
                check_path: security_check
                login_path: login
                enable_csrf: true

            logout:
                path: logout
                target: homepage

    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false

    role_hierarchy:
        ROLE_USER:        ~
        ROLE_TEAMLEAD:    ROLE_USER
        ROLE_ADMIN:       ROLE_TEAMLEAD
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: '^/auth', roles: PUBLIC_ACCESS }
        - { path: '^/(%app_locales%)$', role: PUBLIC_ACCESS }
        - { path: '^/(%app_locales%)/auth', role: PUBLIC_ACCESS }
        - { path: '^/(%app_locales%)/login', role: PUBLIC_ACCESS }
        - { path: '^/(%app_locales%)/register', role: PUBLIC_ACCESS }
        - { path: '^/(%app_locales%)/resetting', role: PUBLIC_ACCESS }
        - { path: '^/(%app_locales%)/', roles: ROLE_USER }
        - { path: '^/api', roles: IS_AUTHENTICATED_REMEMBERED }
