# ================================================================================
# SAML Services
# ================================================================================

services:

    App\Saml\Provider\SamlProvider:
        arguments: ['@App\Repository\UserRepository', '@security.user.provider.concrete.kimai_internal', '@App\Configuration\SamlConfiguration']

    App\Saml\Security\SamlAuthenticationSuccessHandler:
        parent: security.authentication.success_handler
